name: Code checks

on:
  push:
  workflow_call:

env:
  POETRY_VERSION: 2.1.0

jobs:
  test-library:
    name: Test the library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Get full Python version
        id: full-python-version
        shell: bash
        run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
  
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

      - name: Install the library
        run: poetry install -v || poetry install -vvv

      - name: Test the library
        run: poetry task check-all
  test-action:
    name: Test the action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install the action
        uses: ./

      - name: Test the action
        shell: bash
        run: |
          gha-timer start --name "A short test"
          gha-timer elapsed --outcome success --name "A short test"
          gha-timer start --name "A longer test"
          sleep 1
          gha-timer elapsed --outcome success --name "A longer test"
          gha-timer start --name "Something that will fail"
          sleep 1
          gha-timer elapsed --outcome failure --name "Something that will fail"
          gha-timer start --name "Something that gets cancelled"
          sleep 1
          gha-timer elapsed --outcome cancelled --name "Something that gets cancelled"
          gha-timer start --name "Something that gets skipped"
          sleep 1
          gha-timer elapsed --outcome skipped --name "Something that gets skipped"
          gha-timer stop 
